### PR TITLE
Updated proto with DeleteMessage

### PR DESCRIPTION
**Pull request by admo-1**
cf. OWL-69

Just delete in Elastic-Search

### CODE REVIEW

**Review by AppliNH — APPROVED** [review]
Sounds good to me !

**Review by AppliNH — CHANGES_REQUESTED** [review]
We need to use the ID in the request

**Comment by S-HENR** [comment]
> We need to use the message ID in the request (+ the chatroom ID ?)

It would be better to do it that way ! If a message ID cannot be find in two different chatrooms, i think the chatroom ID would not be mandatory.

**Review by AppliNH — COMMENTED** [review]
> > We need to use the message ID in the request (+ the chatroom ID ?)
> 
> It would be better to do it that way ! If a message ID cannot be find in two different chatrooms, i think the chatroom ID would not be mandatory.

The chatroom ID *is* mandatory. Else you can't delete the right document (message ID) in the right index (chatroom ID)

**Review by AppliNH — APPROVED** [review]

**Review by vgalin — APPROVED** [review]
Sounds good to me.

**Pull request merged**
