### PR TITLE
Owl 55 front

### PR DESCRIPTION
**Pull request by S-HENR**

### CODE REVIEW

**Review by AppliNH — CHANGES_REQUESTED** [review]
Maybe remove the title "Information about <USERNAME>" it's not really relevant

**Comment by AppliNH** [comment]
By the way, it would be nice that clicking on a name on a message also allows to access this modal

**Comment by AppliNH** [comment]
And please, as @vgalin said, can you make the background a bit dark / blurry when this modal appears

**Comment by S-HENR** [comment]
Changes applies

**Pull request merged**
